on: [push, pull_request]

name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: setup Docker
        if: "contains( ${{ matrix.platform }}, 'ubuntu')"
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          make test && make coverage
        env:
          XDEV_CC_IMAGE: xuper/emcc:1.0.1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

      - name: Counter size check
        run: |
          make && bash scripts/test/counter_size.sh
        env:
          XDEV_CC_IMAGE: xuper/emcc:llvm_backend
